# Generated by Django 2.1.1 on 2018-11-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Complete'), (3, 'Pending')], default=2),
        ),
    ]
