# Generated by Django 2.1.1 on 2018-11-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20181120_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='completed',
        ),
    ]
